---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: addressbook
      name: addressbook
    spec:
      containers:
      - image: mithileshindurkar/myimage
        name: app
---
apiVersion: v1
kind: Service
metadata:
  name: addressbook-svc
spec:
  ports:
  - port: 8080
  selector:
    app: addressbook
  type: LoadBalancer
